"""baseline: core productivity, startup CRM, AI tables

Revision ID: 147f444aa934
Revises: 
Create Date: 2026-08-23 23:53:01.990168
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '147f444aa934'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_calendar_external')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_user_id'), ['user_id'], unique=False)

    op.create_table('daily_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('incomplete_tasks', sa.Integer(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('productivity_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_review_user_date')
    )
    with op.batch_alter_table('daily_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reviews_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_goal_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_parent_goal_id'), ['parent_goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_objective', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_startups_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_startups_user_id'), ['user_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_role'), ['role'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('metric', sa.String(length=120), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_startup_id'), ['startup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_status'), ['status'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contacted', sa.DateTime(), nullable=True),
    sa.Column('next_follow_up', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_startup_id'), ['startup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_startup_id'), ['startup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.String(length=15), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_user_id'), ['user_id'], unique=False)

    op.create_table('focus_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('planned_duration', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('outreach_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_activities_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_activities_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_activities_startup_id'), ['startup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_activities_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_activities_type'), ['type'], unique=False)

    op.create_table('time_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_blocks_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_blocks_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_blocks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_blocks_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_blocks_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_blocks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_blocks_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_blocks_type'))
        batch_op.drop_index(batch_op.f('ix_time_blocks_task_id'))
        batch_op.drop_index(batch_op.f('ix_time_blocks_status'))
        batch_op.drop_index(batch_op.f('ix_time_blocks_start_time'))
        batch_op.drop_index(batch_op.f('ix_time_blocks_end_time'))

    op.drop_table('time_blocks')
    with op.batch_alter_table('outreach_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_activities_type'))
        batch_op.drop_index(batch_op.f('ix_outreach_activities_timestamp'))
        batch_op.drop_index(batch_op.f('ix_outreach_activities_startup_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_activities_result'))
        batch_op.drop_index(batch_op.f('ix_outreach_activities_lead_id'))

    op.drop_table('outreach_activities')
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_task_id'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_status'))

    op.drop_table('focus_sessions')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_user_id'))

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_goal_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_deadline'))
        batch_op.drop_index(batch_op.f('ix_tasks_area'))

    op.drop_table('tasks')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_metrics_startup_id'))
        batch_op.drop_index(batch_op.f('ix_metrics_name'))

    op.drop_table('metrics')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_startup_id'))

    op.drop_table('leads')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_status'))
        batch_op.drop_index(batch_op.f('ix_experiments_startup_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_role'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_startups_user_id'))
        batch_op.drop_index(batch_op.f('ix_startups_status'))

    op.drop_table('startups')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_area'))

    op.drop_table('projects')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_goals_status'))
        batch_op.drop_index(batch_op.f('ix_goals_parent_goal_id'))
        batch_op.drop_index(batch_op.f('ix_goals_area'))

    op.drop_table('goals')
    with op.batch_alter_table('daily_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_reviews_date'))

    op.drop_table('daily_reviews')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_source'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_end_time'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
